sudo: required
services:
  - docker

before_install:
  - docker build -t web-app -f Dockerfile.dev .

script:
  - docker run web-app npm run test

deploy:
  provider: elasticbeanstalk
  region: 'us-west-2'
  app: 'webapp'
  env: 'Webapp-env'
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
  bucket_name: 'telasticbeanstalk-us-west-2-421657422286'
  bucket_path: 'webapp'
  on:
    branch: master
